---
title: "World Happiness Index"
author: "Nguyen Ngo, Jenny Tong, Ava Walters"
date: "12/02/2025"
format: 
  pdf:
    documentclass: article
    # margin: 1 in all sides
    geometry:
      - margin=1in
    
    # no table of content
    toc: false
    
    # figures with captions on top
    fig-pos: "H"
    tbl-cap-location: top
    fig-cap-location: top
 
# prevent warnings and messages
execute:
  echo: false
  warning: false
  message: false
  error: false
---

# Introduction

This report contains statistical analysis on ...

1.  **fiasdjfl**

Each section presents distinct analytical approaches and findings.


# World Happiness Index {#sec-armed}

The analysis focuses specifically...

## Analysis and Visualization
\vspace{8mm}

```{r world-happiness-index-wrangling, include=FALSE}
 # Wrangling Code that will not be shown when rendered

# STEP 1: Load required pacakges
library(tidyverse)
library(readxl) # read excel file
library(janitor)

# STEP 2: Load and clean the Excel dataset
happiness_raw <- read_excel(
  "/Applications/PSU/FALL 2025/STAT 184/week 12/nguyen_repo_practice/Sec-3_FP_NguyenNgo_AvaWalters_JennyTong/World Happiness Report Data Figure 2.1.xlsx",
sheet = "Data for Figure 2.1 (2011–2024)"
) %>%
  # standardize column names
  clean_names()

# STEP 3: Filter for 2024 data
# select important columns
happiness_2024 <-  happiness_raw %>% 
  filter (year == 2024) %>% 
  # rename columns
  select(
    country = country_name,
    rank,
    life_evaluation = life_evaluation_3_year_average,
    gdp = explained_by_log_gdp_per_capita,
    social_support = explained_by_social_support,
    health_life_expectancy = explained_by_healthy_life_expectancy,
    freedom = explained_by_freedom_to_make_life_choices,
    generosity = explained_by_generosity,
    corruption = explained_by_perceptions_of_corruption,
    dystopia_residual
  ) %>% 
  # fix incomplete rows and convert ranks to integers
  mutate(
    rank = as.integer(rank),
    across(c(life_evaluation:corruption), as.numeric)  
  ) %>% 
  filter(!is.na(rank), !is.na(life_evaluation))

# STEP 4: Calculate the Sensitivity Metrics
happiness_sensitivity <- happiness_2024 %>% 
  # order by descending life evaluation
  arrange(desc(life_evaluation)) %>% 
  mutate(
    life_eval_diff = life_evaluation - lead(life_evaluation), 
    rank_diff = rank - lead(rank),
    sensitivity = abs(rank_diff / life_eval_diff), # measures sensitivity
    sensitivity_group = cut(sensitivity,
                            breaks = c(0, 5, 10, 20, Inf),
                            Labels = c("Low", "Medium", "High", "Very High")
                            )
  ) %>% 
  filter(!is.na(sensitivity))

# STEP 5: Compute Correlation of Factors w/ Rank
factor_correlations <- happiness_2024 %>%
select(rank, life_evaluation, gdp, corruption, social_support,
health_life_expectancy, freedom, generosity) %>% 
cor(use = "complete.obs") %>% # compute correlation matrix
as.data.frame() %>%
rownames_to_column("factor") %>% # convert rownames to a column
select(factor, correlation_with_rank = rank)

# STEP 6: Top 10 Happiest Countries Table
top_10 <- happiness_2024 %>% 
  # select 10 smallest ranks
  slice_min(rank, n = 10) %>% 
  select(country, rank, life_evaluation, gdp, corruption)

# STEP 7: Create Bottom 10 Least Happiest Countries Table
bottom_10 <- happiness_2024 %>% 
  # select 10 largest ranks
  slice_max(rank, n = 10) %>% 
  select(country, rank, life_evaluation, gdp, corruption)

# STEP 8: A summary Statistics Table, if needed
summary_stats <- happiness_2024 %>% 
  summarize(
    # count countries
    n_countries = n(),
    avg_life_eval = mean(life_evaluation, na.rm = TRUE),
    avg_gdp = mean(gdp, na.rm = TRUE),
    avg_corruption - mean(corruption, na.rm = TRUE),
    life_eval_range = max(life_evaluation) - min(life_evaluation),
    rank_range = max(rank) - min(rank)
  )
```

```{r display-visualization, echo=FALSE}
# actual displaying stpe
#| label: change-label-in-this-format
#| tbl-cap: "caption for visualizaiton"
# Step 10: 


```

\vspace{8mm}

## Narrative Text ( check rubric again)